all:
	g++ -std=c++17 -O3 cxl_replay_logparser.cc -o cxl_replay_logparser -I /usr/bin/include

debug:
	g++ -std=c++17 -O0 -g -rdynamic cxl_replay_logparser.cc -o cxl_replay_logparser -I /usr/bin/include