all:
	g++ -std=c++17 -O3 cxl_type2_test_logparser.cc -o cxl_type2_test_logparser -I /usr/bin/include

debug:
	g++ -std=c++17 -O0 -g -rdynamic cxl_type2_test_logparser.cc -o cxl_type2_test_logparser -I /usr/bin/include